# Site wide configuration

title: Cristian Consonni's page
locale: en_US
theme: minimal-mistakes-jekyll
url: https://consonni.dev
baseurl:

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments.rb
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Cristian Consonni
  avatar: bio-photo-eurecat.jpg
  bio: "Ph.D. in Computer Science, free software activist, physicist and storyteller"
  email: cristian.consonni(at)eurecat(dot)org
  disqus-shortname: consonni-dev
  twitter: CristianCantoro
  facebook: cristian.consonni
  google:
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: CristianCantoro
  stackoverflow: https://stackoverflow.com/users/2377454/cristiancantoro
  linkedin: cristianconsonni
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  keybase: cristiancantoro

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb",
          "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec",
          "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock",
          "LICENSE", "README.md", "bin", ".deployignore", ".environment",
          "datasets/_wikilinkgraphs",
          "datasets/wikilinkgraphs/_wikilinkgraphs",
          "datasets/wikilinkgraphs-rawwikilinks/_wikilinkgraphs",
          "datasets/wikilinkgraphs-redirects/_wikilinkgraphs",
          "datasets/wikilinkgraphs-snapshots/_wikilinkgraphs",
          "datasets/wikilinkgraphs/_wikilinkgraphs",
          "datasets/wikilinkgraphs-resolved-redirects/_wikilinkgraphs",
          "datasets/wikilinkgraphs-rawwikilinks-snapshots/_wikilinkgraphs",
          "datasets/wikilinkgraphs-revisionlist/_wikilinkgraphs"]
