# Site wide configuration

title: Cristian Consonni's page
locale: en_US
url: http://disi.unitn.it/~consonni


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Cristian Consonni
  avatar: bio-photo.jpg
  bio: "Computer science PhD student, free software activist, physicist and storyteller"
  email: cristian.consonni(at)unitn(dot)it
  disqus-shortname: CristianCantoro
  twitter: CristianCantoro
  facebook: cristian.consonni
  google:
    plus: CristianConsonni
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: CristianCantoro
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: cristianconsonni
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb",
		  "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec",
		  "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock",
		  "LICENSE", "README.md", "bin", ".deployignore", ".environment"]
